[project]
name = "videoanalytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "av>=16.0.1",
    "matplotlib>=3.10.8",
    "notebook>=7.4.7",
    "numpy>=2.3.5",
    "torch>=2.9.1",
]
